spring.application.name=player-service-hamza
server.port=8081
app.discovery.url=http://localhost:8761
spring.datasource.url=jdbc:h2:mem:playersdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
