spring.application.name=game-engine-service
server.port=8080
discovery.url=http://localhost:8761
services.player.name=player-service-hamza
services.question.name=question-catalog-service
services.score.name=score-service
